esphome:
  name: keg-scale
  friendly_name: Keg Scale
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true
  on_boot: 
    priority: -10
    then:
      - logger.set_level: WARN
      - globals.set:
          id: debug_logging_enabled
          value: 'false'
      - logger.log: "Debug logging disabled on startup"      

esp8266:
  board: esp01_1m
  restore_from_flash: True

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome

wifi:
  # Set up a wifi access point using the device name above
  ap:

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:
